export const useWalletAccounts = (): any => {
    const data = `{
        "accounts":{
           "__typename":"AccountsResponse",
           "accounts":[
              {
                 "__typename":"Account",
                 "activatedAt":"2021-11-29T02:29:15.567Z",
                 "available":{
                    "__typename":"Money",
                    "amount":"0.00",
                    "currency":"TAUD"
                 },
                 "balance":{
                    "__typename":"Money",
                    "amount":"0.00",
                    "currency":"TAUD"
                 },
                 "createdAt":"2021-11-29T02:29:15.567Z",
                 "currency":"TAUD",
                 "deactivatedAt":null,
                 "deactivatedReason":null,
                 "id":"96382d49-925d-426d-b330-50cdcc3e60c6",
                 "name":null,
                 "pendingIn":{
                    "__typename":"Money",
                    "amount":"0.00",
                    "currency":"TAUD"
                 },
                 "pendingOut":{
                    "__typename":"Money",
                    "amount":"0.00",
                    "currency":"TAUD"
                 },
                 "stake":{
                    "__typename":"Stake",
                    "amountClaimedTillDate":{
                       "__typename":"Money",
                       "amount":"0.00000000",
                       "currency":"TAUD"
                    },
                    "id":"a799c6d3-204d-4bdf-b588-e409d118a9c6",
                    "lastAmountClaimed":{
                       "__typename":"Money",
                       "amount":"0.00000000",
                       "currency":"TAUD"
                    },
                    "lastInterestCalculatedAt":null,
                    "nextInterestCalculatedAt":"2021-11-30T00:00:00.000+00:00",
                    "pool":{
                       "__typename":"Pool",
                       "currentInterestRate":{
                          "__typename":"InterestRate",
                          "displayInterestRate":"4.01%"
                       },
                       "id":"6242517a-a1ad-46b8-8bee-26da8a9a2d9a",
                       "name":"Apollo"
                    },
                    "status":"available",
                    "userId":"d9bef376-2b40-412c-90b9-d2bfcdf28b0b"
                 },
                 "status":"active",
                 "type":"crypto",
                 "updatedAt":"2021-11-29T02:29:15.567Z",
                 "userId":"d9bef376-2b40-412c-90b9-d2bfcdf28b0b",
                 "version":1
              },
              {
                 "__typename":"Account",
                 "activatedAt":"2021-11-18T05:56:14.413Z",
                 "available":{
                    "__typename":"Money",
                    "amount":"0.00000000",
                    "currency":"ETH"
                 },
                 "balance":{
                    "__typename":"Money",
                    "amount":"0.00000000",
                    "currency":"ETH"
                 },
                 "createdAt":"2021-11-18T05:56:14.413Z",
                 "currency":"ETH",
                 "deactivatedAt":null,
                 "deactivatedReason":null,
                 "id":"db83e610-2481-4a0a-8e1a-e6d9b8c78bcc",
                 "name":null,
                 "pendingIn":{
                    "__typename":"Money",
                    "amount":"0.00000000",
                    "currency":"ETH"
                 },
                 "pendingOut":{
                    "__typename":"Money",
                    "amount":"0.00000000",
                    "currency":"ETH"
                 },
                 "stake":null,
                 "status":"active",
                 "type":"crypto",
                 "updatedAt":"2021-11-18T05:56:14.413Z",
                 "userId":"d9bef376-2b40-412c-90b9-d2bfcdf28b0b",
                 "version":1
              },
              {
                 "__typename":"Account",
                 "activatedAt":"2021-11-18T05:56:14.239Z",
                 "available":{
                    "__typename":"Money",
                    "amount":"0.00000000",
                    "currency":"BTC"
                 },
                 "balance":{
                    "__typename":"Money",
                    "amount":"0.00000000",
                    "currency":"BTC"
                 },
                 "createdAt":"2021-11-18T05:56:14.239Z",
                 "currency":"BTC",
                 "deactivatedAt":null,
                 "deactivatedReason":null,
                 "id":"92034fe3-6552-4ebb-beab-45f78bdfff9b",
                 "name":null,
                 "pendingIn":{
                    "__typename":"Money",
                    "amount":"0.00000000",
                    "currency":"BTC"
                 },
                 "pendingOut":{
                    "__typename":"Money",
                    "amount":"0.00000000",
                    "currency":"BTC"
                 },
                 "stake":null,
                 "status":"active",
                 "type":"crypto",
                 "updatedAt":"2021-11-18T05:56:14.239Z",
                 "userId":"d9bef376-2b40-412c-90b9-d2bfcdf28b0b",
                 "version":1
              },
              {
                 "__typename":"Account",
                 "activatedAt":"2021-11-18T05:56:14.113Z",
                 "available":{
                    "__typename":"Money",
                    "amount":"0.00",
                    "currency":"AUD"
                 },
                 "balance":{
                    "__typename":"Money",
                    "amount":"0.00",
                    "currency":"AUD"
                 },
                 "createdAt":"2021-11-18T05:56:14.113Z",
                 "currency":"AUD",
                 "deactivatedAt":null,
                 "deactivatedReason":null,
                 "id":"bb15e09e-dd23-4bcc-8be1-7fb193d0d2fa",
                 "name":null,
                 "pendingIn":{
                    "__typename":"Money",
                    "amount":"0.00",
                    "currency":"AUD"
                 },
                 "pendingOut":{
                    "__typename":"Money",
                    "amount":"0.00",
                    "currency":"AUD"
                 },
                 "stake":null,
                 "status":"active",
                 "type":"fiat",
                 "updatedAt":"2021-11-18T05:56:14.113Z",
                 "userId":"d9bef376-2b40-412c-90b9-d2bfcdf28b0b",
                 "version":1
              }
           ]
        }
     }`

    return JSON.parse(data);
}
